version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/apps/api/trader-assistant/trading-dashboard"
    schedule: { interval: "weekly" }
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
